// Code generated by protoc-gen-go.
// source: github.com/micro/auth-srv/proto/oauth2/oauth2.proto
// DO NOT EDIT!

/*
Package oauth2 is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/auth-srv/proto/oauth2/oauth2.proto

It has these top-level messages:
	Token
	AuthorizeRequest
	AuthorizeResponse
	TokenRequest
	TokenResponse
*/
package oauth2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Token struct {
	AccessToken  string   `protobuf:"bytes,1,opt,name=access_token" json:"access_token,omitempty"`
	TokenType    string   `protobuf:"bytes,2,opt,name=token_type" json:"token_type,omitempty"`
	RefreshToken string   `protobuf:"bytes,3,opt,name=refresh_token" json:"refresh_token,omitempty"`
	ExpiresIn    int64    `protobuf:"varint,4,opt,name=expires_in" json:"expires_in,omitempty"`
	ExpiresAt    int64    `protobuf:"varint,5,opt,name=expires_at" json:"expires_at,omitempty"`
	Scopes       []string `protobuf:"bytes,6,rep,name=scopes" json:"scopes,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AuthorizeRequest struct {
	// code, token
	ResponseType string   `protobuf:"bytes,1,opt,name=response_type" json:"response_type,omitempty"`
	ClientId     string   `protobuf:"bytes,2,opt,name=client_id" json:"client_id,omitempty"`
	Scopes       []string `protobuf:"bytes,3,rep,name=scopes" json:"scopes,omitempty"`
	State        string   `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
	RedirectUri  string   `protobuf:"bytes,5,opt,name=redirect_uri" json:"redirect_uri,omitempty"`
}

func (m *AuthorizeRequest) Reset()                    { *m = AuthorizeRequest{} }
func (m *AuthorizeRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthorizeRequest) ProtoMessage()               {}
func (*AuthorizeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AuthorizeResponse struct {
	Code  string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	State string `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	// implicit response
	Token *Token `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *AuthorizeResponse) Reset()                    { *m = AuthorizeResponse{} }
func (m *AuthorizeResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthorizeResponse) ProtoMessage()               {}
func (*AuthorizeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthorizeResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type TokenRequest struct {
	ClientId     string `protobuf:"bytes,1,opt,name=client_id" json:"client_id,omitempty"`
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret" json:"client_secret,omitempty"`
	Code         string `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	// password, client_credentials, authorization_code, refresh_token
	GrantType    string `protobuf:"bytes,4,opt,name=grant_type" json:"grant_type,omitempty"`
	RedirectUri  string `protobuf:"bytes,5,opt,name=redirect_uri" json:"redirect_uri,omitempty"`
	RefreshToken string `protobuf:"bytes,6,opt,name=refresh_token" json:"refresh_token,omitempty"`
}

func (m *TokenRequest) Reset()                    { *m = TokenRequest{} }
func (m *TokenRequest) String() string            { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()               {}
func (*TokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type TokenResponse struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *TokenResponse) Reset()                    { *m = TokenResponse{} }
func (m *TokenResponse) String() string            { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()               {}
func (*TokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TokenResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterType((*Token)(nil), "Token")
	proto.RegisterType((*AuthorizeRequest)(nil), "AuthorizeRequest")
	proto.RegisterType((*AuthorizeResponse)(nil), "AuthorizeResponse")
	proto.RegisterType((*TokenRequest)(nil), "TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "TokenResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Oauth2 service

type Oauth2Client interface {
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...client.CallOption) (*AuthorizeResponse, error)
	Token(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*TokenResponse, error)
}

type oauth2Client struct {
	c           client.Client
	serviceName string
}

func NewOauth2Client(serviceName string, c client.Client) Oauth2Client {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "oauth2"
	}
	return &oauth2Client{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *oauth2Client) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...client.CallOption) (*AuthorizeResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Oauth2.Authorize", in)
	out := new(AuthorizeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oauth2Client) Token(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*TokenResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Oauth2.Token", in)
	out := new(TokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Oauth2 service

type Oauth2Handler interface {
	Authorize(context.Context, *AuthorizeRequest, *AuthorizeResponse) error
	Token(context.Context, *TokenRequest, *TokenResponse) error
}

func RegisterOauth2Handler(s server.Server, hdlr Oauth2Handler) {
	s.Handle(s.NewHandler(&Oauth2{hdlr}))
}

type Oauth2 struct {
	Oauth2Handler
}

func (h *Oauth2) Authorize(ctx context.Context, in *AuthorizeRequest, out *AuthorizeResponse) error {
	return h.Oauth2Handler.Authorize(ctx, in, out)
}

func (h *Oauth2) Token(ctx context.Context, in *TokenRequest, out *TokenResponse) error {
	return h.Oauth2Handler.Token(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x4f, 0xbb, 0x40,
	0x10, 0xc5, 0xcb, 0x9f, 0x42, 0xc2, 0xfc, 0x4b, 0x63, 0x37, 0x9a, 0x90, 0x9e, 0x1a, 0x0e, 0xa6,
	0x17, 0x21, 0x69, 0xfd, 0x02, 0x9e, 0x3c, 0x9a, 0x18, 0xef, 0x84, 0x6e, 0xc7, 0xb2, 0xd1, 0xb2,
	0x74, 0x77, 0x31, 0xea, 0xc9, 0x9b, 0x5f, 0x5b, 0x58, 0x76, 0x29, 0xb5, 0x89, 0xa7, 0x76, 0x5f,
	0x26, 0xf3, 0x7e, 0xef, 0x31, 0xb0, 0xde, 0x31, 0x55, 0xd4, 0x9b, 0x84, 0xf2, 0x7d, 0xba, 0x67,
	0x54, 0xf0, 0x34, 0xaf, 0x55, 0x71, 0x23, 0xc5, 0x5b, 0x5a, 0x09, 0xae, 0x78, 0xca, 0xdb, 0xf7,
	0xca, 0xfc, 0x24, 0x5a, 0x8b, 0xbf, 0x1c, 0xf0, 0x9e, 0xf8, 0x0b, 0x96, 0xe4, 0x12, 0x26, 0x39,
	0xa5, 0x28, 0x65, 0xa6, 0xda, 0x77, 0xe4, 0x2c, 0x9c, 0x65, 0x40, 0x08, 0x80, 0x7e, 0x66, 0xea,
	0xa3, 0xc2, 0xe8, 0x9f, 0xd6, 0xae, 0x20, 0x14, 0xf8, 0x2c, 0x50, 0x16, 0x66, 0xd4, 0xb5, 0xa3,
	0xf8, 0x5e, 0xb1, 0x46, 0xcf, 0x58, 0x19, 0x8d, 0x1b, 0xcd, 0x1d, 0x6a, 0xb9, 0x8a, 0x3c, 0xad,
	0x4d, 0xc1, 0x97, 0x94, 0x57, 0x28, 0x23, 0x7f, 0xe1, 0x2e, 0x83, 0xf8, 0x00, 0x17, 0x77, 0x0d,
	0x11, 0x17, 0xec, 0x13, 0x1f, 0xf1, 0x50, 0xa3, 0x54, 0x9d, 0x85, 0xac, 0x78, 0x29, 0xb1, 0x73,
	0xee, 0x68, 0x66, 0x10, 0xd0, 0x57, 0x86, 0xa5, 0xca, 0xd8, 0xd6, 0xc0, 0x1c, 0xb7, 0xb9, 0xed,
	0x36, 0x12, 0x82, 0x27, 0x55, 0xae, 0x50, 0x03, 0x04, 0x6d, 0x2a, 0x81, 0xdb, 0x06, 0x80, 0xaa,
	0xac, 0x16, 0x4c, 0x23, 0x04, 0xf1, 0x3d, 0xcc, 0x06, 0x96, 0x9d, 0x0f, 0x99, 0xc0, 0x98, 0xf2,
	0xad, 0xb5, 0xea, 0xf7, 0xd8, 0xcc, 0xde, 0x31, 0xeb, 0xff, 0x95, 0x9f, 0xe8, 0xd2, 0xe2, 0x6f,
	0x07, 0x26, 0xfa, 0x9f, 0x05, 0x3f, 0x21, 0x74, 0x6c, 0x5d, 0x46, 0x92, 0x48, 0x05, 0x2a, 0xb3,
	0xd1, 0xda, 0xf5, 0xe5, 0xed, 0x44, 0xde, 0xcc, 0xe8, 0xb4, 0x7f, 0xb0, 0x9f, 0xb7, 0xef, 0xeb,
	0x48, 0xd7, 0x10, 0x1a, 0x10, 0x13, 0xa7, 0x27, 0x76, 0x86, 0xc4, 0xab, 0x02, 0xfc, 0x07, 0x7d,
	0x00, 0xe4, 0x16, 0x82, 0xbe, 0x04, 0x32, 0x4b, 0x7e, 0x7f, 0x83, 0x39, 0x49, 0xce, 0x3a, 0x8a,
	0x47, 0x64, 0x69, 0xef, 0x25, 0x4c, 0x86, 0xc1, 0xe7, 0xd3, 0xe4, 0xc4, 0x3e, 0x1e, 0x6d, 0x7c,
	0x7d, 0x61, 0xeb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xc6, 0x20, 0xb7, 0x98, 0x02, 0x00,
	0x00,
}
