// Code generated by protoc-gen-go.
// source: github.com/micro/auth-srv/proto/oauth2/oauth2.proto
// DO NOT EDIT!

/*
Package oauth2 is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/auth-srv/proto/oauth2/oauth2.proto

It has these top-level messages:
	Token
	AuthorizeRequest
	AuthorizeResponse
	TokenRequest
	TokenResponse
	RevokeRequest
	RevokeResponse
*/
package oauth2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Token struct {
	AccessToken  string   `protobuf:"bytes,1,opt,name=access_token" json:"access_token,omitempty"`
	TokenType    string   `protobuf:"bytes,2,opt,name=token_type" json:"token_type,omitempty"`
	RefreshToken string   `protobuf:"bytes,3,opt,name=refresh_token" json:"refresh_token,omitempty"`
	ExpiresAt    int64    `protobuf:"varint,4,opt,name=expires_at" json:"expires_at,omitempty"`
	Scopes       []string `protobuf:"bytes,5,rep,name=scopes" json:"scopes,omitempty"`
	// metadata associated with the token
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Token) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type AuthorizeRequest struct {
	// code, token (not supported)
	ResponseType string   `protobuf:"bytes,1,opt,name=response_type" json:"response_type,omitempty"`
	ClientId     string   `protobuf:"bytes,2,opt,name=client_id" json:"client_id,omitempty"`
	Scopes       []string `protobuf:"bytes,3,rep,name=scopes" json:"scopes,omitempty"`
	State        string   `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
	RedirectUri  string   `protobuf:"bytes,5,opt,name=redirect_uri" json:"redirect_uri,omitempty"`
}

func (m *AuthorizeRequest) Reset()                    { *m = AuthorizeRequest{} }
func (m *AuthorizeRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthorizeRequest) ProtoMessage()               {}
func (*AuthorizeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AuthorizeResponse struct {
	Code  string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	State string `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	// implicit response
	Token *Token `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *AuthorizeResponse) Reset()                    { *m = AuthorizeResponse{} }
func (m *AuthorizeResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthorizeResponse) ProtoMessage()               {}
func (*AuthorizeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthorizeResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type TokenRequest struct {
	ClientId     string `protobuf:"bytes,1,opt,name=client_id" json:"client_id,omitempty"`
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret" json:"client_secret,omitempty"`
	Code         string `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	// password (not supported), client_credentials, authorization_code, refresh_token
	GrantType    string `protobuf:"bytes,4,opt,name=grant_type" json:"grant_type,omitempty"`
	RedirectUri  string `protobuf:"bytes,5,opt,name=redirect_uri" json:"redirect_uri,omitempty"`
	RefreshToken string `protobuf:"bytes,6,opt,name=refresh_token" json:"refresh_token,omitempty"`
	// scopes can be added for client_credentials request
	Scopes []string `protobuf:"bytes,7,rep,name=scopes" json:"scopes,omitempty"`
	// metadata to be stored with a token that's generated
	Metadata map[string]string `protobuf:"bytes,8,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *TokenRequest) Reset()                    { *m = TokenRequest{} }
func (m *TokenRequest) String() string            { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()               {}
func (*TokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TokenRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type TokenResponse struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *TokenResponse) Reset()                    { *m = TokenResponse{} }
func (m *TokenResponse) String() string            { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()               {}
func (*TokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TokenResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type RevokeRequest struct {
	AccessToken string `protobuf:"bytes,1,opt,name=access_token" json:"access_token,omitempty"`
}

func (m *RevokeRequest) Reset()                    { *m = RevokeRequest{} }
func (m *RevokeRequest) String() string            { return proto.CompactTextString(m) }
func (*RevokeRequest) ProtoMessage()               {}
func (*RevokeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type RevokeResponse struct {
}

func (m *RevokeResponse) Reset()                    { *m = RevokeResponse{} }
func (m *RevokeResponse) String() string            { return proto.CompactTextString(m) }
func (*RevokeResponse) ProtoMessage()               {}
func (*RevokeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*Token)(nil), "Token")
	proto.RegisterType((*AuthorizeRequest)(nil), "AuthorizeRequest")
	proto.RegisterType((*AuthorizeResponse)(nil), "AuthorizeResponse")
	proto.RegisterType((*TokenRequest)(nil), "TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "TokenResponse")
	proto.RegisterType((*RevokeRequest)(nil), "RevokeRequest")
	proto.RegisterType((*RevokeResponse)(nil), "RevokeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Oauth2 service

type Oauth2Client interface {
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...client.CallOption) (*AuthorizeResponse, error)
	Token(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*TokenResponse, error)
	Revoke(ctx context.Context, in *RevokeRequest, opts ...client.CallOption) (*RevokeResponse, error)
}

type oauth2Client struct {
	c           client.Client
	serviceName string
}

func NewOauth2Client(serviceName string, c client.Client) Oauth2Client {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "oauth2"
	}
	return &oauth2Client{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *oauth2Client) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...client.CallOption) (*AuthorizeResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Oauth2.Authorize", in)
	out := new(AuthorizeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oauth2Client) Token(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*TokenResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Oauth2.Token", in)
	out := new(TokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oauth2Client) Revoke(ctx context.Context, in *RevokeRequest, opts ...client.CallOption) (*RevokeResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Oauth2.Revoke", in)
	out := new(RevokeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Oauth2 service

type Oauth2Handler interface {
	Authorize(context.Context, *AuthorizeRequest, *AuthorizeResponse) error
	Token(context.Context, *TokenRequest, *TokenResponse) error
	Revoke(context.Context, *RevokeRequest, *RevokeResponse) error
}

func RegisterOauth2Handler(s server.Server, hdlr Oauth2Handler) {
	s.Handle(s.NewHandler(&Oauth2{hdlr}))
}

type Oauth2 struct {
	Oauth2Handler
}

func (h *Oauth2) Authorize(ctx context.Context, in *AuthorizeRequest, out *AuthorizeResponse) error {
	return h.Oauth2Handler.Authorize(ctx, in, out)
}

func (h *Oauth2) Token(ctx context.Context, in *TokenRequest, out *TokenResponse) error {
	return h.Oauth2Handler.Token(ctx, in, out)
}

func (h *Oauth2) Revoke(ctx context.Context, in *RevokeRequest, out *RevokeResponse) error {
	return h.Oauth2Handler.Revoke(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x93, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0xeb, 0x6e, 0xb3, 0x34, 0x93, 0x6c, 0x68, 0xac, 0x22, 0xad, 0xc2, 0xa5, 0x5a, 0x89,
	0xaa, 0x12, 0xaa, 0x57, 0x4a, 0x39, 0x20, 0x6e, 0x1c, 0x10, 0x27, 0x84, 0x54, 0x71, 0x5f, 0xb9,
	0xce, 0xd0, 0xac, 0xda, 0xc4, 0x5b, 0xdb, 0x1b, 0x11, 0xde, 0x83, 0x47, 0xe2, 0x99, 0xb8, 0xe2,
	0xf8, 0x4f, 0x92, 0x6d, 0x11, 0x97, 0x9e, 0xb2, 0xfe, 0x34, 0x99, 0xf9, 0x7d, 0xdf, 0xd8, 0x70,
	0x75, 0x5b, 0x9b, 0x79, 0x7b, 0xc3, 0x84, 0x5c, 0x94, 0x8b, 0x5a, 0x28, 0x59, 0xf2, 0xd6, 0xcc,
	0x2f, 0xb5, 0x5a, 0x95, 0x8d, 0x92, 0x46, 0x96, 0x72, 0x73, 0x9e, 0x86, 0x1f, 0xe6, 0xb4, 0xe2,
	0x37, 0x81, 0xde, 0x37, 0x79, 0x87, 0x4b, 0x7a, 0x0a, 0x43, 0x2e, 0x04, 0x6a, 0x5d, 0x99, 0xcd,
	0x39, 0x27, 0x67, 0xe4, 0xa2, 0x4f, 0x29, 0x80, 0x3b, 0x56, 0x66, 0xdd, 0x60, 0x7e, 0xe8, 0xb4,
	0x57, 0x90, 0x29, 0xfc, 0xae, 0x50, 0xcf, 0x43, 0x69, 0x12, 0x4b, 0xf1, 0x47, 0x53, 0x5b, 0xbd,
	0xe2, 0x26, 0x3f, 0xb2, 0x5a, 0x42, 0x47, 0x90, 0x6a, 0x21, 0x1b, 0xd4, 0x79, 0xef, 0x2c, 0xb1,
	0x35, 0xe7, 0x70, 0xbc, 0x40, 0xc3, 0x67, 0xdc, 0xf0, 0x3c, 0xb5, 0xca, 0x60, 0x7a, 0xca, 0xdc,
	0x78, 0xf6, 0x25, 0xc8, 0x9f, 0x96, 0x46, 0xad, 0x27, 0x25, 0x64, 0x1d, 0x81, 0x0e, 0x20, 0xb9,
	0xc3, 0x75, 0x80, 0xca, 0xa0, 0xb7, 0xe2, 0xf7, 0x6d, 0xe0, 0xf9, 0x70, 0xf8, 0x9e, 0x14, 0x0f,
	0x70, 0xf2, 0xd1, 0xda, 0x92, 0xaa, 0xfe, 0x89, 0xd7, 0xf8, 0xd0, 0xa2, 0x36, 0x9e, 0x53, 0x37,
	0x72, 0xa9, 0xd1, 0xe3, 0xfb, 0x7f, 0x8f, 0xa1, 0x2f, 0xee, 0x6b, 0x5c, 0x9a, 0xaa, 0x9e, 0x05,
	0x47, 0x3b, 0xcc, 0xc4, 0x61, 0xda, 0x01, 0xda, 0x70, 0x83, 0xce, 0x45, 0x7f, 0x13, 0x8d, 0xc2,
	0x99, 0x75, 0x26, 0x4c, 0xd5, 0xaa, 0xda, 0x7a, 0xb1, 0x6a, 0xf1, 0x19, 0xc6, 0x7b, 0x23, 0xfd,
	0x1c, 0x3a, 0x84, 0x23, 0x21, 0x67, 0xb8, 0x03, 0xf5, 0x7d, 0x62, 0x70, 0xbd, 0x5d, 0x60, 0x83,
	0x69, 0xea, 0xad, 0x17, 0x7f, 0x08, 0x0c, 0xdd, 0x57, 0x04, 0xef, 0x10, 0x92, 0x98, 0x79, 0x90,
	0x34, 0x0a, 0x85, 0x26, 0x74, 0x8c, 0xe3, 0xb6, 0x1b, 0xb8, 0x55, 0xdc, 0xd6, 0x38, 0xb7, 0xff,
	0x61, 0x7f, 0xba, 0xc2, 0xf4, 0x51, 0x0e, 0x2f, 0x5c, 0x0e, 0x97, 0x7b, 0xeb, 0x3a, 0x76, 0xeb,
	0x7a, 0xcd, 0xf6, 0x49, 0x9f, 0xbb, 0xb5, 0x73, 0xc8, 0x42, 0xbb, 0x10, 0xdf, 0x36, 0x21, 0xd2,
	0x49, 0xe8, 0x0d, 0x64, 0xd7, 0xb8, 0xb2, 0x9f, 0x31, 0xa1, 0x7f, 0x5e, 0xd6, 0xe2, 0x04, 0x46,
	0xb1, 0xcc, 0xf7, 0x9b, 0xfe, 0x22, 0x90, 0x7e, 0x75, 0xf7, 0x9d, 0xbe, 0x83, 0xfe, 0x76, 0x5d,
	0x74, 0xcc, 0x1e, 0xdf, 0x96, 0x09, 0x65, 0x4f, 0xb6, 0x59, 0x1c, 0xd0, 0x8b, 0xf8, 0x3c, 0xb2,
	0x8e, 0xf1, 0xc9, 0x88, 0x75, 0xc0, 0x6d, 0xe5, 0x5b, 0x48, 0xfd, 0x70, 0x3a, 0x62, 0x1d, 0xd8,
	0xc9, 0x4b, 0xd6, 0xa5, 0x2a, 0x0e, 0x6e, 0x52, 0xf7, 0xfa, 0xae, 0xfe, 0x06, 0x00, 0x00, 0xff,
	0xff, 0xe8, 0x57, 0xfa, 0x11, 0xb4, 0x03, 0x00, 0x00,
}
