// Code generated by protoc-gen-go.
// source: github.com/micro/auth-srv/proto/account/account.proto
// DO NOT EDIT!

/*
Package go_micro_srv_auth_account is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/auth-srv/proto/account/account.proto

It has these top-level messages:
	Record
	ReadRequest
	ReadResponse
	CreateRequest
	CreateResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	SearchRequest
	SearchResponse
*/
package go_micro_srv_auth_account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Record struct {
	// uuid
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// service or user
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	// service name, username, etc
	ClientId string `protobuf:"bytes,3,opt,name=client_id" json:"client_id,omitempty"`
	// we leave this blank in responses
	// used for update and create
	ClientSecret string            `protobuf:"bytes,4,opt,name=client_secret" json:"client_secret,omitempty"`
	Metadata     map[string]string `protobuf:"bytes,5,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// unix timestamp
	Created int64 `protobuf:"varint,6,opt,name=created" json:"created,omitempty"`
	// unix timestamp
	Updated int64 `protobuf:"varint,7,opt,name=updated" json:"updated,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Record) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ReadResponse struct {
	Account *Record `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadResponse) GetAccount() *Record {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateRequest struct {
	// If id is blank, one will be generated
	Account *Record `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateRequest) GetAccount() *Record {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type UpdateRequest struct {
	// Id and client_id cannot be changed
	Account *Record `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateRequest) GetAccount() *Record {
	if m != nil {
		return m.Account
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type SearchRequest struct {
	ClientId string `protobuf:"bytes,1,opt,name=client_id" json:"client_id,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Limit    int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset   int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SearchResponse struct {
	Accounts []*Record `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchResponse) GetAccounts() []*Record {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "go.micro.srv.auth.account.Record")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.srv.auth.account.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.srv.auth.account.ReadResponse")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.auth.account.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.auth.account.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "go.micro.srv.auth.account.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "go.micro.srv.auth.account.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.srv.auth.account.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.srv.auth.account.DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.srv.auth.account.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.srv.auth.account.SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Account service

type AccountClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type accountClient struct {
	c           client.Client
	serviceName string
}

func NewAccountClient(serviceName string, c client.Client) AccountClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.auth.account"
	}
	return &accountClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *accountClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Account service

type AccountHandler interface {
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterAccountHandler(s server.Server, hdlr AccountHandler) {
	s.Handle(s.NewHandler(&Account{hdlr}))
}

type Account struct {
	AccountHandler
}

func (h *Account) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.AccountHandler.Read(ctx, in, out)
}

func (h *Account) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.AccountHandler.Create(ctx, in, out)
}

func (h *Account) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.AccountHandler.Update(ctx, in, out)
}

func (h *Account) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.AccountHandler.Delete(ctx, in, out)
}

func (h *Account) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.AccountHandler.Search(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x5d, 0xeb, 0x2e, 0xd9, 0xbe, 0x2c, 0x05, 0x2c, 0x21, 0x65, 0xe5, 0x32, 0x72, 0x80, 0x72,
	0xc0, 0x91, 0x32, 0x21, 0x21, 0x6e, 0x63, 0xec, 0x88, 0x90, 0x8a, 0x38, 0x70, 0x9a, 0x3c, 0xc7,
	0x5b, 0x23, 0x92, 0x38, 0x24, 0xce, 0xa4, 0xfe, 0x5d, 0x4e, 0xfc, 0x0c, 0x1c, 0xdb, 0x81, 0x66,
	0x02, 0xaf, 0x62, 0xa7, 0x2a, 0x2f, 0xef, 0x7b, 0xef, 0xfb, 0xf2, 0x9e, 0x0a, 0x6f, 0x6e, 0x72,
	0xb9, 0xee, 0xae, 0x08, 0x13, 0x65, 0x52, 0xe6, 0xac, 0x11, 0x09, 0xed, 0xe4, 0xfa, 0x75, 0xdb,
	0xdc, 0x26, 0x75, 0x23, 0xa4, 0x7a, 0x64, 0x4c, 0x74, 0x95, 0x1c, 0x7e, 0x89, 0x46, 0xf1, 0xf1,
	0x8d, 0x20, 0x9a, 0x4e, 0x14, 0x93, 0xf4, 0x23, 0xc4, 0x12, 0xe2, 0x1f, 0x13, 0xf0, 0x56, 0x9c,
	0x89, 0x26, 0xc3, 0x00, 0xd3, 0x3c, 0x8b, 0x26, 0x27, 0x93, 0xe5, 0x21, 0x3e, 0x82, 0x99, 0xdc,
	0xd4, 0x3c, 0x9a, 0xea, 0xa7, 0x27, 0x70, 0xc8, 0x8a, 0x9c, 0x57, 0xf2, 0x52, 0x11, 0x90, 0x86,
	0x9e, 0x42, 0x68, 0xa1, 0x96, 0xb3, 0x86, 0xcb, 0x68, 0xa6, 0xe1, 0x33, 0x38, 0x28, 0xb9, 0xa4,
	0x19, 0x95, 0x34, 0xda, 0x3f, 0x41, 0xcb, 0x20, 0x4d, 0xc8, 0x3f, 0xcd, 0x89, 0x31, 0x26, 0x1f,
	0xed, 0xc4, 0x45, 0x25, 0x9b, 0x0d, 0x7e, 0x04, 0xbe, 0x12, 0xa4, 0x92, 0x67, 0x91, 0xa7, 0x34,
	0x51, 0x0f, 0x74, 0x75, 0xa6, 0x01, 0xbf, 0x07, 0x16, 0x09, 0x84, 0xe3, 0x91, 0x00, 0xd0, 0x37,
	0xbe, 0xb1, 0xab, 0x87, 0xb0, 0x7f, 0x4b, 0x8b, 0xce, 0xee, 0xfe, 0x6e, 0xfa, 0x76, 0x12, 0x1f,
	0x43, 0xb0, 0xe2, 0x34, 0x5b, 0xf1, 0xef, 0x1d, 0x6f, 0xe5, 0xf6, 0xa1, 0xf1, 0x7b, 0x38, 0x32,
	0xaf, 0xda, 0x5a, 0x54, 0x2d, 0xc7, 0x29, 0xf8, 0x76, 0x3b, 0x4d, 0x08, 0xd2, 0xe7, 0xf7, 0xee,
	0x1f, 0x9f, 0x43, 0x78, 0xae, 0x37, 0x1e, 0x0c, 0xfe, 0x47, 0xe4, 0x31, 0xcc, 0x07, 0x11, 0xb3,
	0x4a, 0x2f, 0xfb, 0x45, 0xdf, 0xfd, 0x40, 0xd9, 0x41, 0xc4, 0xca, 0x3e, 0x83, 0xf0, 0x03, 0x2f,
	0xf8, 0x1f, 0xd9, 0xed, 0xcf, 0xa1, 0xe8, 0xc3, 0x4b, 0x4b, 0xff, 0x04, 0xe1, 0x67, 0x4e, 0x1b,
	0xb6, 0x1e, 0xe8, 0xa3, 0x32, 0xfc, 0xad, 0x2d, 0x2a, 0x80, 0x22, 0x2f, 0x73, 0xa9, 0x9b, 0x82,
	0xf0, 0x1c, 0x3c, 0x71, 0x7d, 0xdd, 0xda, 0x8a, 0xa0, 0xf8, 0x02, 0xe6, 0x83, 0xa0, 0xfd, 0xe6,
	0xa7, 0x70, 0x60, 0xb7, 0x6e, 0x95, 0x20, 0xda, 0xe9, 0xb0, 0xf4, 0x27, 0x02, 0xff, 0xcc, 0x40,
	0xf8, 0x2b, 0xcc, 0xfa, 0x10, 0xf1, 0x0b, 0xe7, 0xd8, 0xef, 0x02, 0x2c, 0x5e, 0xde, 0xcb, 0xb3,
	0xc7, 0xef, 0xe1, 0x4b, 0xf0, 0x4c, 0x2c, 0x78, 0xe9, 0x18, 0x1a, 0xc5, 0xbf, 0x78, 0xb5, 0x03,
	0x73, 0xdb, 0xc0, 0x04, 0xe4, 0x34, 0x18, 0x15, 0xc1, 0x69, 0x70, 0x27, 0x6d, 0x6d, 0x60, 0x22,
	0x75, 0x1a, 0x8c, 0x2a, 0xe1, 0x34, 0xb8, 0xd3, 0x0f, 0x6d, 0x60, 0x02, 0x75, 0x1a, 0x8c, 0x4a,
	0xe4, 0x34, 0x18, 0xb7, 0x23, 0xde, 0xbb, 0xf2, 0xf4, 0xbf, 0xd8, 0xe9, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x90, 0xd2, 0xfd, 0xf8, 0xfe, 0x04, 0x00, 0x00,
}
